package com.epam.jwd.dao.api;

import com.epam.jwd.dao.entity.AbstractEntity;
import com.epam.jwd.dao.exception.DAOException;

import java.util.List;

/**
 * @author mikh
 * This interface is creted due to DAO Pattern and provide user with CRUD methods and an extra
 * options to find credit cards by user id and find credit cards by bank account id
 * @param <T> the entity that extends AbstractEntity class {@link AbstractEntity}
 * @param <K> the type of entity id field provided from AbstractEntity class {@link AbstractEntity#id}
 */
public interface CreditCardDAO<T extends AbstractEntity<K>, K> {

    /**
     * Save method which provide user with opportunity to save entity to the DataBase
     * @param entity entity to save in DataBase
     * @return the saved entity value with generated by DataBase id
     * @throws DAOException if the connection can't be accepted or save operation
     * was failed
     */
    T save(T entity) throws DAOException;

    /**
     * Method which extracts all values from DataBase and put it to the List {@link List}
     * @return list of entities in current DataBase table
     * @throws DAOException if the connection can't be accepted or findAll operation
     * was failed
     */
    List<T> findAll() throws DAOException;

    /**
     * Method which extracts entity from DataBase with provided id of type {@link AbstractEntity#id}
     * @param id id of provided type to find entity in DataBase
     * @return entity of current type
     * @throws DAOException if the connection can't be accepted or findById operation
     * was failed
     */
    T findById(K id) throws DAOException;

    /**
     * Method which updates some entity fields in DataBase by provided entity
     * @param entity provided entity with updated fields
     * @return updated entity
     * @throws DAOException if the connection can't be accepted or update operation
     * was failed
     */
    T update(T entity) throws DAOException;

    /**
     * Method which deletes current entity from Database by provided entity
     * @param entity entity to delete
     * @throws DAOException if the connection can't be accepted or delete operation
     * was failed
     */
    void delete(T entity) throws DAOException;

    /**
     * Method which extract from DataBase List {@link List} of entities with provided user id
     * @param id id field to find current credit cards in DataBase
     * @return List of founded entities in DataBase with provided id
     * @throws DAOException if the connection can't be accepted or findCreditCardsByUserId operation
     * was failed
     */
    List<T> findCreditCardsByUserId(K id) throws DAOException;

    /**
     * Method which extract from DataBase entity with provided bank account id
     * @param id id field to find current credit card in DataBase
     * @return entity with provided id
     * @throws DAOException if the connection can't be accepted or findCreditCardByBankAccountId operation
     * was failed
     */
    T findCreditCardByBankAccountId(K id) throws DAOException;
}
